feat: Update to latest ipld-explorer-components
ipld/explore.ipld.io pull request #119
Opened 2023-05-25 19:10 UTC by SgtPooki

Note that this code is based on changes included in https://github.com/ipfs/ipld-explorer-components/pull/360 and must wait to be merged until we can publish a new ipld-explorer-components lib once that PR is merged. 

Check out the demo:

https://github.com/ipld/explore.ipld.io/assets/1173416/90802964-9e98-418c-9353-12270b1f71e1

2023-05-25 20:20 UTC, SgtPooki commented on package.json
> +    "ipld-explorer-components": "file:../../ipfs/ipld-explorer-components/ipld-explorer-components-3.0.3.tgz",
will be updated once https://github.com/ipfs/ipld-explorer-components/pull/360 is merged

2023-05-25 20:20 UTC, SgtPooki commented on .env
> +VITE_VERSION=$npm_package_version
part of vite migration

2023-05-25 20:20 UTC, SgtPooki commented on index.html
> +    <link rel="shortcut icon" href="/favicon.ico">
part of vite migration

2023-05-25 20:20 UTC, SgtPooki commented on index.html
> +    <script type="module" src="/src/index.jsx"></script>
part of vite migration

2023-05-25 20:20 UTC, SgtPooki commented on package.json
> +    "test:unit-playwright": "playwright test -c playwright-ct.config.js",
not currently used, but available to run unit tests via playwright if we want to normalize on tests.

2023-05-25 20:20 UTC, SgtPooki commented on src/App.jsx
> +    route: PropTypes.oneOfType([PropTypes.func, PropTypes.element, PropTypes.elementType]).isRequired
fixes an in-app error regarding prop types mismatch.

2023-05-25 20:20 UTC, SgtPooki commented on test/e2e/smoke.test.js
> +//   // Save 3s per run by using the initial page rather than creating a new one!
todo: need to migrate this test code to playwright.

2023-05-26 18:23 UTC, SgtPooki commented
related issue found when doing js-ipfs deprecation: https://github.com/ipfs/js-ipfs/issues/1416

2023-06-28 00:08 UTC, lidel requested changes
Tested latest version from  https://bafybeiepdrogejw7eji6qdbq3hpd3ewuuhecyvf4nyofvhntsbyb3w7tqa.on.fleek.co

@SgtPooki looks ok for available content, but trying to fetch something new timeouts bit too early? Lmk if I got things right.

I tried to add a PDF and explore its CID (`bafybeibms6xfhs4kx3tun7dg6bjbj5obca7yj43cl5jl3pc2n7muw6ipfm`) and the gateway request for the root block  was stuck in "Pending":

> ![2023-06-28_02-01](https://github.com/ipld/explore.ipld.io/assets/157609/1be1fbe1-085f-4785-b48f-8fe80db1c0b2)
 
 
 and after a while that request got cancelled:
 
 >  ![2023-06-28_02-02](https://github.com/ipld/explore.ipld.io/assets/157609/708563df-599d-42fb-a69d-de23977d03bb)


So two problems:
1. Why is request for single block in `Pending`? It should fhit gateway asap, before  anything else. Are WebTransport requests still suffocating the request queue browser allocates to the page?
2. Why it cancels (timeouts?) so fast? As long gateway request is in progress or pending, it should not timeout.

2023-07-04 00:47 UTC, SgtPooki commented
> Why is request for single block in Pending? It should [hit] gateway asap, before anything else. Are WebTransport requests still suffocating the request queue browser allocates to the page?

Helia should not be making any requests except for to the delegatedClient via kubo-rpc-client: https://github.com/ipfs/ipld-explorer-components/blob/ca19310defb84611f55c46b1efd399217ba4a8c6/src/lib/init-helia.ts#L28-L63

> Why it cancels (timeouts?) so fast? As long gateway request is in progress or pending, it should not timeout.

Mostly to keep the site responsive and gateway-friendly. I've currently got the [timeout set to 30 seconds](https://github.com/ipfs/ipld-explorer-components/blob/ca19310defb84611f55c46b1efd399217ba4a8c6/src/lib/get-raw-block.ts#L108C98-L108C103). I've heard significant feedback from users that explore.ipld.io would spin and spin and they never knew if their content was going to load. I think a much better approach is to fail early, and have the users refresh/retry if they want. 

Were you able to fetch your content from http://ipfs.io/ipfs/bafybeibms6xfhs4kx3tun7dg6bjbj5obca7yj43cl5jl3pc2n7muw6ipfm directly? Maybe you removed the content, but I just attempted to access it and it failed after 

We shouldn't have users guessing whether a request is going to succeed or not. Also, for failed gateway requests, the gateway keeps the connection open for up to 2 minutes, and sends back almost 1K of data: 

![image](https://github.com/ipld/explore.ipld.io/assets/1173416/e4a6a1fd-1766-4fb0-8504-2bdcf6fc9f5a)

If we cancel requests that are pending for 30 seconds, we can free up the gateway to do other work, and the user can re-request things if they want. If there is a different timeout value you think would be better or a better way to handle this without significant feature work, then please let me know.

---

#### Drawbacks

* The code is currently set to try the [gateways in serial](https://github.com/ipfs/ipld-explorer-components/blob/ca19310defb84611f55c46b1efd399217ba4a8c6/src/lib/get-raw-block.ts#L76) which means if ipfs.io takes more than `timeout` ms, dweb.link is never attempted. If ipfs.io takes less than `timeout` ms, then dweb.link is never attempted. These could be made parallel since we removed the non-delegated Helia fetch attempts. 

#### Other things to think about 

* Higher default timeout - Gives users the expectation that something will resolve, when in all likelihood, if it hasn't resolved in 30 seconds, it probably won't. In my experience improving ipld-explorer-components, 30 seconds was a pretty nice spot. 
* Better error message - I looked into displaying a better error message previously, but the way the network requests are hidden so deep in ipld-explorer-components, it was a larger task than I wanted to fit into https://github.com/ipfs/ipld-explorer-components/pull/360.
    * It would be great to be able to show more details about failed fetch attempts ("failed to load via ipfs.io: Gateway Timeout", "failed to load via dweb.link: Gateway Timeout", "failed to load via local node: request blocked", etc..) and also where we were able to successfully fetch the request from
* Configurable timeouts - Allow users to specify whether they want the request to timeout (i'm just curiously browsing), or whether they're willing to wait for long enough to load it (I need to actually explore this content for some reason)
* Stagger parallel gateway requests - We should not broadcast to all gateways at the same time, but we could delay the requests to subsequent gateways by something like`timeout/2` for example. 
* Separate timeouts + staggered requests - We could have a global-get-raw-block-timeout and stagger requests to gateways by (N+1 gateways tested / global-get-raw-block-timeout)

2023-07-07 17:08 UTC, lidel approved these changes
Thank you @SgtPooki, failing fast at 30s mark makes sense as a trade-off,  
the problem is bad UX on timeout – user adds data to their local node, then tries to inspect it, timeouts, app looks broken:

>  ![2023-07-07_19-02](https://github.com/ipld/explore.ipld.io/assets/157609/216d7275-1620-450e-b703-3c0a678c4cd6)

One way to fix this without rewriting the entire thing is to inspect error before printing the red box and if it is timeout/promise cancellation,  replace it with friendly "Failed to fetch content in 30s, refresh page to retry or try different CID."?  It would be good enough to unblock this PR.

Since  ipld-explorer-components@4.0.0  is released, would it be ok to merge this as-is, and fill issues for any remaining work ("Drawbacks", "Other things to think about"), and do it  in future PRs (if we have time).

Would be shame if this PR got stuck in review forever: It is already better than the old version! :)

2023-07-07 17:35 UTC, SgtPooki commented
> Failed to fetch content in 30s, refresh page to retry or try different CID

I see your approval, but I will work on that error message prior to merging.

2023-07-12 02:15 UTC, SgtPooki commented
@lidel PR out to address this in ipld-explorer-components: https://github.com/ipfs/ipld-explorer-components/pull/378

2023-07-12 17:23 UTC, SgtPooki commented
new preview url, https://bafybeif65hxysjwygngoahx7v6a2ouzsfi4y24u7ovr4vd5ya4jhq7ngjy.on.fleek.co/, updated in description. 

tested new error message at https://bafybeif65hxysjwygngoahx7v6a2ouzsfi4y24u7ovr4vd5ya4jhq7ngjy.on.fleek.co/#/explore/bafybeibms6xfhs4kx3tun7dg6bjbj5obca7yj43cl5jl3pc2n7muw6ipfm

![image](https://github.com/ipld/explore.ipld.io/assets/1173416/7209aea2-b99d-4955-9cb8-9479e2a627cc)

2023-07-12 17:24 UTC, merged

2023-07-12 17:29 UTC, SgtPooki commented
Changes deployed on explore.ipld.io.

https://explore.ipld.io/#/explore/bafybeibms6xfhs4kx3tun7dg6bjbj5obca7yj43cl5jl3pc2n7muw6ipfm shows the error message appropriately.